<?php
/*
 * BroScriptLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/21/2016
 */

namespace BroScriptLib;

use BroScriptLib\Controllers;

/**
 * BroScriptLib client class
 */
class BroScriptClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($userKey = NULL, $scriptKey = NULL)
    {
        Configuration::$userKey = $userKey ? $userKey : Configuration::$userKey;
        Configuration::$scriptKey = $scriptKey ? $scriptKey : Configuration::$scriptKey;
    }
 
    /**
     * Singleton access to API controller
     * @return Controllers\APIController The *Singleton* instance
     */
    public function getClient()
    {
        return Controllers\APIController::getInstance();
    }
}