<?php
/*
 * BroScriptLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/21/2016
 */

namespace BroScriptLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class. 
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'http://api.broscript.ru';

    /**
     * User Key
     * @var string
     */
    /**
     * @todo Replace the $userKey with an appropriate value
     */
    public static $userKey = '';

    /**
     * Script Key
     * @var string
     */
    /**
     * @todo Replace the $scriptKey with an appropriate value
     */
    public static $scriptKey = '';

}
